channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs=18
  - pip
  - ipywidgets==8.0.2
  - jupyter-offlinenotebook==0.2.2
  - jupyter-resource-usage==0.7.0
  - jupyterlab==3.4.8
  - jupyterhub-singleuser==3.1.1
  - notebook==6.4.12
  - nteract_on_jupyter==2.1.3
  - pandas=1.5.3
  - scipy=1.10.1
